import Head from "next/head";
import TopBar from "@/components/templates/TopBar";
import Presentation from "@/components/templates/Presentation";
import AboutMe from "@/components/templates/AboutMe";
import MyWorks from "@/components/templates/MyWorks";
import ContactMe from "@/components/templates/ContactMe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bravos.me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/bravos-icon.svg" />
      </Head>
      <main className="bg-white">
        <div className="mt-4 flex flex-col justify-center space-y-28">
          <TopBar />
          <Presentation />
          <AboutMe />
          <MyWorks />
          <ContactMe />
        </div>
      </main>
    </>
  );
}
